quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=oracle123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/ventas

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

quarkus.http.port=8083

producto-api/mp-rest/url=http://localhost:8080
cliente-api/mp-rest/url=http://localhost:8082

quarkus.fault-tolerance.enabled=true